### PR TITLE
Hello Microverse project pull request

### PR DESCRIPTION
**Pull request by MarvelGrace**
It is a simple html and css project.

### CODE REVIEW

**Review by jmonto55 — CHANGES_REQUESTED** [review]
# STATUS: REQUIRED CHANGES 🟡

Hi @MarvelGrace  👋🏽, 

Good job so far! 
There are some issues that you still need to work on to go to the next project but you are almost there!

AlmostThereGIF (2)





## Required Changes ♻️

Great work implementing the README file provided by Microverse 💯. However, please kindly ensure to make the following changes on it:
- [x] Remove the Microverse logo.
- [x] Remove all instructions on how to fill the README file (i. e. > Describe your project in 1 or 2 sentences).
- [x]  Fill the form with custom information related to the Hello Microverse project, currently, it has the template's genric information.
- [x]  Currently, the name of the file containing the MIT license is` MIT.md`, but you are specifying a file called `LICENSE.md` in the footer part of your README file, please kindly ensure to fix the name. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Efiamotu-1 — COMMENTED** [review]
Hi @MarvelGrace , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request
 
You have submitted a project, that has already been merged making it difficult for anyone reviewing to review properly. please kindly ensure that you do not merge your branches before they are approved by a reviewer, just like you have done in this case. you can choose to open a new pull request and resubmit with the new changes made or you can just open this branch again and add the required changes.
- [ ] Also you have failed to implement any of the required changes from the previous reviewer. i kindly suggest that you pay close attention to his review summary as he listed out to you the steps to take so your project meets the project requirements. :+1: 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by MarvelGrace** [comment]
Well, thanks, @Efiamotu-1, I tried to resolve the conflict, but, there is a difficulty on that. Therefore, may I have to create a new branch and go with the new process and submit for code review again?

Gratitude,
God's best!

**Comment by Efiamotu-1** [comment]
@MarvelGrace you can choose to create a new branch make all the necessary changes and resubmit however take note that when creating the pull request summary you are to add a link to this pr where a previous change had been requested so that the next reviewer is aware of the previously required implementation and can go ahead to review your project.

**Pull request merged**
